"use client";

import { FormEvent, useState } from "react";
import styles from "./template-patrimonio.module.css";

const pillars = [
  ["Visão integrada", "Uma decisão revela impactos nas demais.", "Organizamos relações antes de priorizar ações."],
  ["Liquidez", "O presente precisa sustentar o futuro.", "Reservas e fluxo preservam margem para escolher."],
  ["Proteção", "Riscos precisam de nome e responsável.", "Proteção começa por dependências reais."],
  ["Investimentos", "A carteira cumpre um papel no plano.", "Produto vem depois de prazo, objetivo e critério."],
  ["Sucessão", "Continuidade se prepara antes da urgência.", "Pessoas, documentos e decisões entram no mesmo mapa."],
];

const map = [
  ["Fluxo e liquidez", "Quanto precisa permanecer disponível para preservar escolhas?", "Fluxo, compromissos, reservas e prazos.", "Distribuição e prioridade.", "Próximos passos compatíveis com o presente."],
  ["Proteção", "Quais dependências poderiam interromper o plano?", "Pessoas, responsabilidades e riscos.", "Priorizar proteções.", "Responsabilidades mais claras."],
  ["Investimentos", "Qual papel cada recurso precisa cumprir?", "Objetivo, prazo, liquidez e risco.", "Estruturar critérios.", "Carteira conectada ao plano."],
  ["Patrimônio", "Como bens e responsabilidades estão organizados?", "Documentos, dependências e decisões.", "Coordenar informações.", "Visão integrada do patrimônio."],
  ["Sucessão", "O que precisa estar preparado para assegurar continuidade?", "Pessoas e especialistas necessários.", "Organizar próximos passos.", "Continuidade com contexto."],
];

const services = [
  ["Organização financeira", "Como distribuir recursos entre compromissos, reservas e objetivos?", "Leitura do fluxo, da liquidez e das prioridades para tornar os próximos passos visíveis."],
  ["Proteção e riscos", "Quais responsabilidades precisam estar cobertas?", "Mapeamento das pessoas, riscos e dependências que fazem parte do seu contexto."],
  ["Investimentos", "Qual papel cada recurso tem no seu plano?", "Critérios de prazo, liquidez e objetivo vêm antes de qualquer produto."],
  ["Patrimônio e sucessão", "O que precisa estar coordenado para o futuro?", "Documentos, responsáveis e especialistas entram no mesmo mapa."],
];

export default function TemplatePatrimonio() {
  const [pillar, setPillar] = useState(0);
  const [mapIndex, setMapIndex] = useState(0);
  const [service, setService] = useState(0);
  const [menuOpen, setMenuOpen] = useState(false);
  const [sent, setSent] = useState(false);

  function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); setSent(true); }

  return <div className={styles.page}>
    <a className={styles.skip} href="#conteudo">Pular para o conteúdo</a>
    <header className={styles.header}>
      <a className={styles.brand} href="#inicio"><span>ARQUIVO</span><i>—</i><small>PATRIMÔNIO</small></a>
      <nav className={styles.nav}><a href="#metodo">Método</a><a href="#atuacao">Frentes de atuação</a><a href="#para-quem">Para quem</a><a href="#escritorio">Escritório</a><a href="#faq">Dúvidas</a></nav>
      <a className={styles.headerAction} href="#contato">Agendar conversa</a>
      <button className={styles.menuButton} onClick={() => setMenuOpen(!menuOpen)} aria-expanded={menuOpen}>Menu <span>+</span></button>
      {menuOpen && <nav className={styles.mobileNav}><a href="#metodo" onClick={() => setMenuOpen(false)}>Método</a><a href="#atuacao" onClick={() => setMenuOpen(false)}>Frentes de atuação</a><a href="#para-quem" onClick={() => setMenuOpen(false)}>Para quem</a><a href="#escritorio" onClick={() => setMenuOpen(false)}>Escritório</a><a href="#faq" onClick={() => setMenuOpen(false)}>Dúvidas</a><a href="#contato" onClick={() => setMenuOpen(false)}>Agendar conversa</a></nav>}
    </header>
    <main id="conteudo">
      <section className={styles.hero} id="inicio"><div className={styles.heroCopy}><p className={styles.eyebrow}>Planejamento financeiro e patrimonial</p><h1>Planejar patrimônio é <em>organizar escolhas.</em></h1><p className={styles.lead}>Uma visão estruturada para conectar patrimônio, família, empresa e futuro — antes de recomendar qualquer produto.</p><div className={styles.actions}><a className={styles.button} href="#contato">Agendar conversa inicial <span>→</span></a><a className={styles.textLink} href="#metodo">Conhecer o método <span>↓</span></a></div><p className={styles.trust}>[CIDADE/UF] <i>·</i> Atendimento online para todo o Brasil <i>·</i> Confidencialidade</p></div><figure className={styles.heroPhoto}><div><span>REUNIÃO DE PLANEJAMENTO</span><b>01</b></div><figcaption>Imagem demonstrativa — substitua por fotografia autorizada.</figcaption></figure></section>
      <section className={styles.pillars}><div className={styles.pillarTabs} role="tablist">{pillars.map((item, i) => <button key={item[0]} onClick={() => setPillar(i)} aria-selected={pillar === i}>{item[0]}</button>)}</div><div className={styles.pillarDetail}><span>0{pillar + 1} / 05</span><strong>{pillars[pillar][1]}</strong><p>{pillars[pillar][2]}</p></div></section>
      <section className={styles.tension}><h2>O patrimônio não acontece <em>em partes.</em></h2><div><p>Renda, empresa, investimentos, família, proteção e futuro costumam ser analisados separadamente. As decisões, porém, afetam umas às outras.</p><p>O planejamento começa quando tudo passa a fazer parte do mesmo contexto.</p></div><ul><li>Decisões importantes sem um critério comum.</li><li>Informações espalhadas entre profissionais e documentos.</li><li>Dúvida sobre o que fazer agora e o que pode esperar.</li></ul></section>
      <section className={styles.method} id="metodo"><div className={styles.wrap + " " + styles.methodGrid}><div><span className={styles.sectionTag}>COMO TRABALHAMOS</span><h2>Método antes de produto.</h2><p>Nosso método organiza decisões antes de discutir produtos.</p></div><ol>{[["Contexto completo", "O que existe, quem participa e quais decisões se conectam."], ["Decisões registradas", "Motivos, responsáveis e próximos passos permanecem claros."], ["Critérios explícitos", "Escolhas podem ser compreendidas e revistas."], ["Coordenação e revisão", "O plano acompanha mudanças e especialistas necessários."]].map((item, i) => <li key={item[0]}><b>0{i + 1}</b><strong>{item[0]}</strong><span>{item[1]}</span></li>)}</ol><aside className={styles.decisionRecord}><header><span>Registro de decisão</span><b>DEMONSTRAÇÃO</b></header><dl><div><dt>Decisão em pauta</dt><dd>Prioridade para os próximos 12 meses</dd></div><div><dt>Motivo</dt><dd>Conectar liquidez e objetivo familiar</dd></div><div><dt>Pessoas envolvidas</dt><dd>[RESPONSÁVEIS]</dd></div><div><dt>Critério adotado</dt><dd>[CRITÉRIO VALIDADO]</dd></div><div><dt>Próximo passo</dt><dd>[AÇÃO DEFINIDA]</dd></div><div><dt>Data de revisão</dt><dd>[DATA]</dd></div></dl></aside></div></section>
      <section className={styles.map}><div className={styles.wrap + " " + styles.mapGrid}><div><span className={styles.sectionTag}>MAPA PATRIMONIAL</span><h2>Um mapa para decisões que se cruzam.</h2><p>Escolha uma frente para ver a pergunta que orienta o trabalho. O escopo final depende dos serviços reais contratados.</p></div><div className={styles.mapTabs}>{map.map((item, i) => <button key={item[0]} onClick={() => setMapIndex(i)} aria-selected={mapIndex === i}>{item[0]} <span>→</span></button>)}</div><article className={styles.mapPanel}><span>Pergunta central</span><h3>{map[mapIndex][1]}</h3><dl><div><dt>Analisamos</dt><dd>{map[mapIndex][2]}</dd></div><div><dt>Decisão</dt><dd>{map[mapIndex][3]}</dd></div><div><dt>Clareza esperada</dt><dd>{map[mapIndex][4]}</dd></div></dl></article></div></section>
      <section className={styles.process}><div className={styles.wrap}><span className={styles.sectionTag}>ETAPAS</span><h2>Decisões registradas.<br />Próximos passos visíveis.</h2><p>O processo avança por etapas, com entregas e revisões claras.</p><ol>{["Conversa inicial", "Diagnóstico", "Prioridades", "Plano", "Implementação", "Revisão"].map((item, i) => <li key={item}><b>0{i + 1}</b><span>{item}</span></li>)}</ol></div></section>
      <section className={styles.services} id="atuacao"><div className={styles.wrap + " " + styles.servicesGrid}><div><span className={styles.sectionTag}>SERVIÇOS</span><h2>Frentes de atuação.</h2><p>Ative somente os serviços realmente oferecidos. Cada frente explica uma pergunta concreta, não uma promessa.</p></div><div className={styles.serviceList}>{services.map((item, i) => <article key={item[0]} className={service === i ? styles.openService : ""}><button onClick={() => setService(i)} aria-expanded={service === i}><span>{item[0]}</span><b>+</b></button>{service === i && <div><strong>{item[1]}</strong><p>{item[2]}</p></div>}</article>)}</div></div></section>
      <section className={styles.quote}><blockquote>O plano não é uma resposta pronta. É uma estrutura de decisões que precisa caber na sua vida, nas pessoas envolvidas e no tempo disponível.</blockquote><div>{["Contexto", "Prioridade", "Responsáveis", "Prazo", "Critério", "Revisão"].map((item) => <span key={item}>{item}</span>)}</div></section>
      <section className={styles.audience} id="para-quem"><div className={styles.wrap}><span className={styles.sectionTag}>O MÉTODO</span><h2>Para quem o método faz sentido.</h2><div className={styles.audienceGrid}>{[["Famílias", "Quando decisões patrimoniais, proteção e futuro precisam ser vistas em conjunto."], ["Empresários", "Quando vida pessoal e empresa compartilham recursos, riscos e responsabilidades."], ["Profissionais", "Quando a renda cresceu, as escolhas se multiplicaram e falta tempo para coordená-las."], ["Transições", "Aposentadoria, venda de empresa, herança, mudança de país ou reorganização familiar."]].map((item) => <article key={item[0]}><h3>{item[0]}</h3><p>{item[1]}</p></article>)}</div><aside><strong>Talvez não seja o momento ideal quando…</strong><p>Você busca uma recomendação isolada, uma promessa de rentabilidade ou não deseja compartilhar o contexto necessário ao planejamento.</p></aside></div></section>
      <section className={styles.about} id="escritorio"><div className={styles.wrap + " " + styles.aboutGrid}><figure><span>ESCRITÓRIO</span><b>—</b></figure><div><span className={styles.sectionTag}>QUEM SUSTENTA O MÉTODO</span><h2>Quem sustenta o método.</h2><p>Conheça o escritório e a equipe.</p><h3>[NOME DO PLANEJADOR]</h3><p className={styles.role}>[TÍTULO PROFISSIONAL]</p><p>[BIOGRAFIA REAL]</p><div className={styles.credentials}><span>[CERTIFICAÇÃO REAL]</span><span>[FORMAÇÃO REAL]</span><span>[MODELO REAL DE ATENDIMENTO]</span></div></div></div></section>
      <section className={styles.portal}><div className={styles.wrap + " " + styles.portalGrid}><div><span className={styles.sectionTag}>PORTAL DO CLIENTE</span><h2>O plano continua visível entre uma conversa e outra.</h2><p>Quando houver um portal real, apresente tarefas, documentos, objetivos, mensagens e revisões no mesmo lugar.</p><a className={styles.textLink} href="#contato">Acessar portal do cliente <span>→</span></a></div><div className={styles.portalDemo}><header><span>Visão do plano</span><b>DEMONSTRAÇÃO</b></header><div><span>Próxima revisão</span><strong>[DATA]</strong></div><div><span>Decisões em acompanhamento</span><strong>[ITENS]</strong></div><p><i /></p><small>Substitua por um mockup real antes de publicar.</small></div></div></section>
      <section className={styles.faq} id="faq"><div className={styles.wrap + " " + styles.faqGrid}><div><span className={styles.sectionTag}>DÚVIDAS</span><h2>Perguntas antes da primeira conversa.</h2><p>As respostas abaixo são orientações de preenchimento. Substitua pela prática real do escritório.</p></div><div>{[["O que acontece na primeira conversa?", "A conversa organiza o contexto e verifica se o formato de trabalho é adequado, sem antecipar recomendações."], ["Preciso ter todos os documentos prontos?", "Não. A conversa inicial mostra quais informações e pessoas precisam participar de cada próxima etapa."], ["O planejamento inclui indicação de produtos?", "O escopo e as responsabilidades são explicados no momento adequado, depois que o contexto é compreendido."]].map((item, i) => <details key={item[0]} open={i === 0}><summary>{item[0]} <b>+</b></summary><p>{item[1]}</p></details>)}</div></div></section>
      <section className={styles.contact} id="contato"><div className={styles.wrap + " " + styles.contactGrid}><div><span className={styles.sectionTag}>PRÓXIMO PASSO</span><h2>Conheça o método do escritório.</h2><p>Conte qual decisão merece contexto agora. Não informe renda, patrimônio, CPF ou documentos neste formulário.</p><p>Prazo de retorno: <b>[PRAZO REAL DE RETORNO]</b></p></div><form onSubmit={submit}><label>Nome<input required name="name" minLength={2} autoComplete="name" /></label><label>E-mail<input required name="email" type="email" autoComplete="email" /></label><label>WhatsApp<input required name="phone" type="tel" autoComplete="tel" /></label><label className={styles.full}>Decisão ou tema principal<textarea required name="topic" rows={4} placeholder="Ex.: organizar prioridades para uma transição profissional" /></label><label>Preferência de contato<select required defaultValue=""><option value="" disabled>Selecione</option><option>E-mail</option><option>WhatsApp</option><option>Ligação</option></select></label><label className={styles.consent}><input type="checkbox" required /> Concordo com o tratamento dos dados enviados conforme a política de privacidade.</label><button className={styles.button} type="submit">Solicitar conversa inicial <span>→</span></button>{sent && <p className={styles.sent}>Recebemos seu contato. Em breve retornaremos.</p>}</form></div></section>
    </main>
    <footer className={styles.footer}><div className={styles.wrap}><a className={styles.brand} href="#inicio"><span>ARQUIVO</span><i>—</i><small>PATRIMÔNIO</small></a><p>Planejamento para conectar patrimônio, família, empresa e futuro com critérios claros.</p><address>[CIDADE/UF]<br />Atendimento online para todo o Brasil<br />[E-MAIL] · [TELEFONE]</address><div><span>[RAZÃO SOCIAL] · [CNPJ OU IDENTIFICAÇÃO]</span><span>[AVISO LEGAL VALIDADO PARA O SERVIÇO OFERECIDO]</span></div></div></footer>
  </div>;
}
