"use client";

import { FormEvent, useState } from "react";
import styles from "./template-clareza.module.css";

const focusItems: [string, string, string, string[]][] = [
  ["Organizar o presente", "Começar por fluxo, reservas e prioridades.", "O objetivo é criar margem para decisões e reduzir improvisos, sem transformar organização em restrição permanente.", ["Fluxo financeiro", "Reservas e liquidez", "Metas de curto prazo"]],
  ["Preparar uma decisão", "Entender impactos antes de escolher.", "Compra de imóvel, mudança profissional ou decisão familiar entram em um cenário comum.", ["Cenários", "Responsáveis", "Prazos"]],
  ["Estruturar o futuro", "Conectar proteção, aposentadoria e patrimônio.", "O futuro é organizado em premissas que podem ser revisitadas ao longo do tempo.", ["Proteção", "Aposentadoria", "Objetivos de longo prazo"]],
  ["Revisar um plano", "Atualizar critérios quando a vida mudou.", "Planos antigos deixam de guiar decisões atuais por inércia.", ["Mudanças", "Critérios", "Novas prioridades"]],
];
const solutions = [
  ["Organizar o presente", "Como fazer a renda servir ao que importa agora?", "Fluxo, reservas e metas de curto prazo ficam visíveis no mesmo plano."],
  ["Preparar uma decisão", "Como comparar impactos antes de assumir um compromisso?", "Prazos, consequências e pessoas envolvidas passam a fazer parte da conversa."],
  ["Estruturar o futuro", "O que precisa estar preparado para suas escolhas futuras?", "Objetivos, proteção e patrimônio se organizam em hipóteses revisáveis."],
  ["Acompanhamento", "Quando o plano precisa voltar à mesa?", "Mudanças importantes disparam uma nova conversa e a atualização das prioridades."],
];

export default function TemplateClareza() {
  const [focus, setFocus] = useState(0);
  const [solution, setSolution] = useState(0);
  const [menuOpen, setMenuOpen] = useState(false);
  const [sent, setSent] = useState(false);
  function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); setSent(true); }
  return <div className={styles.page}>
    <a className={styles.skip} href="#conteudo">Pular para o conteúdo</a>
    <header className={styles.header}><a className={styles.brand} href="#inicio"><span>CLAREZA</span><i>•</i><small>PLANEJAMENTO</small></a><nav className={styles.nav}><a href="#funciona">Como funciona</a><a href="#solucoes">Soluções</a><a href="#sobre">Sobre</a><a href="#faq">Dúvidas</a></nav><a className={styles.headerAction} href="#contato">Agendar conversa</a><button className={styles.menuButton} onClick={() => setMenuOpen(!menuOpen)} aria-expanded={menuOpen}>Menu <span>+</span></button>{menuOpen && <nav className={styles.mobileNav}><a href="#funciona" onClick={() => setMenuOpen(false)}>Como funciona</a><a href="#solucoes" onClick={() => setMenuOpen(false)}>Soluções</a><a href="#sobre" onClick={() => setMenuOpen(false)}>Sobre</a><a href="#faq" onClick={() => setMenuOpen(false)}>Dúvidas</a><a href="#contato" onClick={() => setMenuOpen(false)}>Agendar conversa</a></nav>}</header>
    <main id="conteudo">
      <section className={styles.hero} id="inicio"><div className={styles.heroCopy}><p className={styles.eyebrow}>Planejamento financeiro para a vida real</p><h1>Seu dinheiro precisa de <em>direção</em>, não de pressão.</h1><p>Planejamento financeiro para transformar escolhas importantes em um caminho possível, acompanhado de perto e revisto quando a vida mudar.</p><div className={styles.actions}><a className={styles.button} href="#contato">Agendar conversa <span>→</span></a><a className={styles.textLink} href="#funciona">Ver como funciona <span>↓</span></a></div><ul><li>Atendimento online para todo o Brasil</li><li>Conversa inicial</li><li>Confidencialidade</li><li>[CERTIFICAÇÃO REAL]</li></ul></div><figure className={styles.heroPhoto}><div><span>CONVERSA QUE COMEÇA PELO CONTEXTO</span><b>→</b></div><figcaption>Imagem demonstrativa — substitua por fotografia autorizada.</figcaption></figure></section>
      <section className={styles.recognition}><div className={styles.wrap}><div><span className={styles.tag}>RECONHECER O MOMENTO</span><h2>Quando tudo parece importante, clareza começa por prioridade.</h2><p>Você não precisa resolver todas as frentes ao mesmo tempo. Precisa entender o que depende do quê.</p></div><div className={styles.recognitionFlow}>{["Muitas metas competem pelo mesmo recurso.", "Investimentos nem sempre estão conectados aos objetivos.", "Renda, reservas e futuro são acompanhados em lugares diferentes.", "Decisões familiares ficam adiadas por falta de contexto.", "O tempo para organizar tudo sozinho quase nunca aparece."].map((item, i) => <p className={i === 0 ? styles.large : ""} key={item}><b>0{i + 1}</b>{item}</p>)}</div></div></section>
      <section className={styles.soft}><div className={styles.wrap + " " + styles.benefits}><div><span className={styles.tag}>O QUE MUDA</span><h2>O que muda quando as escolhas se conectam.</h2></div><div>{[["Prioridades mais claras", "Você consegue diferenciar o que pede ação agora do que precisa apenas ser acompanhado."], ["Decisões com critérios", "As escolhas deixam de depender apenas do impulso ou da urgência do momento."], ["Próximos passos visíveis", "Cada decisão ganha responsável, prazo e uma relação com o restante do plano."], ["Revisões quando a vida muda", "O plano volta à mesa quando renda, família, objetivos ou contexto mudarem."]].map((item) => <article key={item[0]}><b>+</b><h3>{item[0]}</h3><p>{item[1]}</p></article>)}</div></div></section>
      <section className={styles.process} id="funciona"><div className={styles.wrap}><div className={styles.sectionHeading}><div><span className={styles.tag}>O PROCESSO</span><h2>Um processo que você consegue acompanhar.</h2></div><p>Meu método transforma perguntas importantes em prioridades possíveis.</p></div><ol>{["Conversa inicial", "Diagnóstico", "Prioridades", "Plano", "Implementação", "Revisão"].map((item, i) => <li key={item}><b>0{i + 1}</b><span>{item}</span></li>)}</ol></div></section>
      <section className={styles.soft + " " + styles.focus}><div className={styles.wrap + " " + styles.focusGrid}><div><span className={styles.tag}>PRIMEIRO MOVIMENTO</span><h2>Agora em foco.</h2><p>Escolha o momento que mais se parece com o seu. A organização começa pelas perguntas, não por respostas prontas.</p></div><div><div className={styles.focusTabs}>{focusItems.map((item, i) => <button onClick={() => setFocus(i)} aria-selected={focus === i} key={item[0]}>{item[0]}</button>)}</div><div className={styles.focusPanel}><span>MOMENTO SELECIONADO</span><h3>{focusItems[focus][1]}</h3><p>{focusItems[focus][2]}</p><ul>{focusItems[focus][3].map((item) => <li key={item}>{item}</li>)}</ul></div></div></div></section>
      <section className={styles.solutions} id="solucoes"><div className={styles.wrap + " " + styles.solutionsGrid}><div><span className={styles.tag}>FRENTES DE ATUAÇÃO</span><h2>Um plano para a vida real.</h2><p>Ative apenas frentes realmente oferecidas. Cada solução começa por uma pergunta concreta.</p></div><div className={styles.solutionList}>{solutions.map((item, i) => <article key={item[0]} className={solution === i ? styles.open : ""}><button onClick={() => setSolution(i)} aria-expanded={solution === i}><span>{item[0]}</span><b>+</b></button>{solution === i && <div><strong>{item[1]}</strong><p>{item[2]}</p></div>}</article>)}</div></div></section>
      <section className={styles.soft + " " + styles.principles}><div className={styles.wrap}><span className={styles.tag}>COMO ACOMPANHAMOS</span><h2>Planejamento próximo, decisões bem explicadas.</h2><div>{[["◎", "Visão integrada", "As partes são analisadas pelo impacto que exercem umas sobre as outras."], ["≡", "Critérios claros", "Você entende por que uma decisão veio antes da outra."], ["↗", "Plano compreensível", "Documentos e próximos passos usam linguagem que você consegue acompanhar."], ["↻", "Revisão contínua", "Mudanças importantes reabrem o plano com contexto atualizado."]].map((item) => <article key={item[1]}><span>{item[0]}</span><h3>{item[1]}</h3><p>{item[2]}</p></article>)}</div></div></section>
      <section className={styles.personal}><div className={styles.wrap + " " + styles.personalGrid}><blockquote>Você não recebe apenas uma lista de tarefas. Recebe uma forma mais clara de decidir, registrar e revisar.</blockquote><div><h2>O plano considera.</h2><ul>{["Quem participa das decisões", "O que já existe e precisa ser preservado", "O que é prioridade agora", "Quais profissionais precisam ser coordenados", "Quando cada hipótese será revista"].map((item) => <li key={item}>{item}</li>)}</ul></div></div></section>
      <section className={styles.soft + " " + styles.audience}><div className={styles.wrap}><span className={styles.tag}>PARA QUEM</span><h2>Momentos em que ter companhia faz diferença.</h2><div>{[["Vida profissional", "A renda mudou, mas as decisões ainda não encontraram uma ordem."], ["Família", "Objetivos, proteção e responsabilidades precisam conversar."], ["Patrimônio", "Mais bens e investimentos trouxeram mais relações para acompanhar."], ["Transição", "Uma escolha importante precisa de contexto antes de virar compromisso."]].map((item, i) => <article key={item[0]}><span>0{i + 1}</span><p>{item[0]}</p><h3>{item[1]}</h3></article>)}</div></div></section>
      <section className={styles.about} id="sobre"><div className={styles.wrap + " " + styles.aboutGrid}><figure><span>ATENÇÃO E CONTEXTO</span><b>↗</b></figure><div><span className={styles.tag}>QUEM ACOMPANHA</span><h2>O seu momento merece contexto, não respostas prontas.</h2><p>Conheça minha trajetória.</p><h3>[NOME DO PLANEJADOR]</h3><p className={styles.role}>[TÍTULO PROFISSIONAL]</p><p>[BIOGRAFIA REAL]</p><div className={styles.credentials}><span>[CERTIFICAÇÃO REAL]</span><span>[FORMAÇÃO REAL]</span><span>[MODELO REAL DE ATENDIMENTO]</span></div></div></div></section>
      <section className={styles.soft + " " + styles.portal}><div className={styles.wrap + " " + styles.portalGrid}><div><span className={styles.tag}>PORTAL DO CLIENTE</span><h2>Seu plano acessível entre uma conversa e outra.</h2><p>O portal é uma extensão do acompanhamento: ajuda a lembrar próximos passos, documentos e revisões sem substituir a conversa.</p><a className={styles.textLink} href="#contato">Acessar portal do cliente <span>→</span></a></div><div className={styles.portalCard}><header><span>Visão da semana</span><b>DEMONSTRAÇÃO</b></header>{["Revisar decisão [TEMA]", "Organizar documento [TIPO]", "Preparar próxima conversa"].map((item) => <div key={item}><i>✓</i><span>{item}</span></div>)}<small>Substitua por uma tela real do portal.</small></div></div></section>
      <section className={styles.faq} id="faq"><div className={styles.wrap + " " + styles.faqGrid}><div><span className={styles.tag}>DÚVIDAS</span><h2>Perguntas que podem estar passando pela sua cabeça.</h2><p>Use respostas reais, simples e transparentes.</p></div><div>{[["O que acontece na primeira conversa?", "A conversa serve para ouvir o momento, entender o que precisa de clareza e explicar os próximos passos possíveis."], ["Preciso organizar tudo antes de falar?", "Não. A conversa inicial ajuda a entender por onde começar e quais informações serão úteis ao longo do processo."], ["Como funciona o acompanhamento?", "O formato é apresentado de maneira clara, respeitando seu momento e o escopo do trabalho."]].map((item, i) => <details key={item[0]} open={i === 0}><summary>{item[0]}<b>+</b></summary><p>{item[1]}</p></details>)}</div></div></section>
      <section className={styles.contact} id="contato"><div className={styles.wrap + " " + styles.contactGrid}><div><span className={styles.tag}>PRÓXIMO PASSO</span><h2>Vamos entender o seu momento.</h2><p>Conte o que deseja organizar. Não informe renda, patrimônio, CPF ou documentos.</p><p>Prazo de retorno: <b>[PRAZO REAL DE RETORNO]</b></p><a className={styles.textLink} href="#contato">Prefere falar por WhatsApp? <span>→</span></a></div><form onSubmit={submit}><label>Nome<input name="name" required minLength={2} autoComplete="name" /></label><label>E-mail<input name="email" required type="email" autoComplete="email" /></label><label>WhatsApp<input name="phone" required type="tel" autoComplete="tel" /></label><label className={styles.full}>O que deseja organizar?<textarea name="topic" required rows={4} placeholder="Ex.: quero priorizar objetivos antes de uma mudança profissional" /></label><label>Como prefere ser contatado?<select required defaultValue=""><option value="" disabled>Selecione</option><option>E-mail</option><option>WhatsApp</option><option>Ligação</option></select></label><label className={styles.consent}><input type="checkbox" required /> Concordo com o tratamento dos dados conforme a política de privacidade.</label><button className={styles.button} type="submit">Enviar solicitação <span>→</span></button>{sent && <p className={styles.sent}>Recebemos seu contato. Em breve retornaremos.</p>}</form></div></section>
    </main>
    <footer className={styles.footer}><div className={styles.wrap}><a className={styles.brand} href="#inicio"><span>CLAREZA</span><i>•</i><small>PLANEJAMENTO</small></a><p>Planejamento próximo para organizar prioridades e acompanhar decisões importantes.</p><address>[CIDADE/UF]<br />Atendimento online para todo o Brasil<br />[E-MAIL] · [TELEFONE]</address><div><span>[RAZÃO SOCIAL] · [CNPJ OU IDENTIFICAÇÃO]</span><span>[AVISO LEGAL VALIDADO PARA O SERVIÇO OFERECIDO]</span></div></div></footer>
  </div>;
}
