-- Registro de abertura e tempo visível das páginas nativas da Imersão.
-- Materiais da Biblioteca continuam em public.leituras, vinculados a downloads.

create table public.curso_acessos (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users(id) on delete set null,
  email text not null,
  semana_key text not null,
  aberturas integer not null default 1,
  segundos integer not null default 0,
  primeiro_acesso timestamptz not null default now(),
  ultimo_acesso timestamptz not null default now(),

  constraint curso_acessos_email_normalizado check (
    email = lower(btrim(email))
    and char_length(email) between 3 and 254
    and email like '%_@_%._%'
  ),
  constraint curso_acessos_semana_valida check (
    semana_key in (
      'semana-0',
      'semana-1',
      'semana-2',
      'semana-3',
      'semana-4'
    )
  ),
  constraint curso_acessos_aberturas_positivas check (aberturas > 0),
  constraint curso_acessos_segundos_positivos check (segundos >= 0),
  constraint curso_acessos_user_semana_unique unique (user_id, semana_key)
);

comment on table public.curso_acessos is
  'Aberturas e tempo visível agregado das páginas nativas da Imersão.';
comment on column public.curso_acessos.email is
  'Snapshot normalizado do e-mail verificado para relatórios administrativos.';
comment on column public.curso_acessos.segundos is
  'Tempo aproximado com a página da etapa visível; não inclui abas em segundo plano.';

create index curso_acessos_semana_ultimo_idx
  on public.curso_acessos (semana_key, ultimo_acesso desc);
create index curso_acessos_email_ultimo_idx
  on public.curso_acessos (email, ultimo_acesso desc);

alter table public.curso_acessos enable row level security;
revoke all on table public.curso_acessos from public, anon, authenticated;
grant select, insert, update on table public.curso_acessos to service_role;
grant usage, select on sequence public.curso_acessos_id_seq to service_role;

-- Um único upsert evita perder segundos quando dois pulsos chegam juntos.
-- A função só é exposta ao service_role; a rota confere sessão e liberação da etapa.
create or replace function public.curso_acesso_registrar(
  p_user_id uuid,
  p_email text,
  p_semana_key text,
  p_acao text,
  p_segundos integer default 0
)
returns void
language plpgsql
security invoker
set search_path = ''
as $function$
declare
  v_email text := lower(btrim(coalesce(p_email, '')));
  v_agora timestamptz := now();
  v_segundos integer := 0;
begin
  if p_user_id is null then
    raise exception 'user_id obrigatorio' using errcode = '22023';
  end if;
  if p_semana_key not in ('semana-0', 'semana-1', 'semana-2', 'semana-3', 'semana-4') then
    raise exception 'semana invalida' using errcode = '22023';
  end if;
  if p_acao not in ('abrir', 'pulso') then
    raise exception 'acao invalida' using errcode = '22023';
  end if;
  if char_length(v_email) not between 3 and 254 or v_email not like '%_@_%._%' then
    raise exception 'email invalido' using errcode = '22023';
  end if;

  if p_acao = 'pulso' then
    v_segundos := least(greatest(coalesce(p_segundos, 0), 0), 120);
    if v_segundos = 0 then
      return;
    end if;
  end if;

  insert into public.curso_acessos (
    user_id,
    email,
    semana_key,
    aberturas,
    segundos,
    primeiro_acesso,
    ultimo_acesso
  ) values (
    p_user_id,
    v_email,
    p_semana_key,
    1,
    v_segundos,
    v_agora,
    v_agora
  )
  on conflict (user_id, semana_key) do update
  set email = excluded.email,
      aberturas = public.curso_acessos.aberturas
        + case when p_acao = 'abrir' then 1 else 0 end,
      segundos = public.curso_acessos.segundos + v_segundos,
      ultimo_acesso = v_agora;
end;
$function$;

revoke all on function public.curso_acesso_registrar(uuid, text, text, text, integer)
  from public, anon, authenticated;
grant execute on function public.curso_acesso_registrar(uuid, text, text, text, integer)
  to service_role;
