begin;

-- `whitelist.turma_id` continua sendo a matrícula atual. Esta tabela preserva
-- o percurso do aluno mesmo depois que ele é movido para outra turma.
create table if not exists public.aluno_turmas (
  id bigint generated by default as identity primary key,
  email text not null,
  turma_id bigint not null references public.turmas(id) on delete restrict,
  entrou_em timestamptz not null default now(),
  saiu_em timestamptz,
  criado_em timestamptz not null default now(),
  constraint aluno_turmas_email_normalizado check (email = lower(btrim(email))),
  constraint aluno_turmas_periodo_valido check (saiu_em is null or saiu_em >= entrou_em)
);

comment on table public.aluno_turmas is
  'Histórico de matrículas. A linha sem saiu_em representa a turma atual do aluno.';

create unique index if not exists aluno_turmas_uma_ativa_por_aluno_idx
  on public.aluno_turmas (email)
  where saiu_em is null;
create index if not exists aluno_turmas_aluno_periodo_idx
  on public.aluno_turmas (email, entrou_em desc);
create index if not exists aluno_turmas_turma_periodo_idx
  on public.aluno_turmas (turma_id, entrou_em desc);

-- Cada turma aponta para uma edição existente no código em cada etapa. A
-- validação da edição disponível é feita no servidor; o banco aceita `vN`
-- para que uma edição nova possa ser publicada num deploy posterior.
create table if not exists public.turma_conteudo_versoes (
  turma_id bigint not null references public.turmas(id) on delete cascade,
  etapa_key text not null,
  versao text not null default 'v1',
  atualizada_em timestamptz not null default now(),
  primary key (turma_id, etapa_key),
  constraint turma_conteudo_versoes_etapa_valida check (
    etapa_key in ('semana-0', 'semana-1', 'semana-2', 'semana-3', 'semana-4')
  ),
  constraint turma_conteudo_versoes_codigo_valido check (versao ~ '^v[1-9][0-9]*$')
);

comment on table public.turma_conteudo_versoes is
  'Edição de conteúdo em código escolhida pela turma para cada etapa.';

insert into public.aluno_turmas (email, turma_id, entrou_em)
select w.email, w.turma_id, coalesce(w.criado_em, now())
from public.whitelist as w
where w.turma_id is not null
  and not exists (
    select 1 from public.aluno_turmas as h where h.email = w.email and h.saiu_em is null
  );

insert into public.turma_conteudo_versoes (turma_id, etapa_key, versao)
select t.id, etapa.etapa_key, 'v1'
from public.turmas as t
cross join (values
  ('semana-0'), ('semana-1'), ('semana-2'), ('semana-3'), ('semana-4')
) as etapa(etapa_key)
on conflict (turma_id, etapa_key) do nothing;

create or replace function private.registrar_historico_turma_aluno()
returns trigger
language plpgsql
security invoker
set search_path = ''
as $$
begin
  if tg_op = 'INSERT' then
    if new.turma_id is not null then
      insert into public.aluno_turmas (email, turma_id, entrou_em)
      values (new.email, new.turma_id, now());
    end if;
    return new;
  end if;

  if tg_op = 'DELETE' then
    update public.aluno_turmas
    set saiu_em = now()
    where email = old.email and saiu_em is null;
    return old;
  end if;

  if old.turma_id is not distinct from new.turma_id then
    return new;
  end if;

  update public.aluno_turmas
  set saiu_em = now()
  where email = old.email and saiu_em is null;

  if new.turma_id is not null then
    insert into public.aluno_turmas (email, turma_id, entrou_em)
    values (new.email, new.turma_id, now());
  end if;
  return new;
end;
$$;

revoke all on function private.registrar_historico_turma_aluno() from public, anon, authenticated;

drop trigger if exists whitelist_historico_turma_insert on public.whitelist;
create trigger whitelist_historico_turma_insert
after insert on public.whitelist
for each row execute function private.registrar_historico_turma_aluno();
drop trigger if exists whitelist_historico_turma_update on public.whitelist;
create trigger whitelist_historico_turma_update
after update of turma_id on public.whitelist
for each row execute function private.registrar_historico_turma_aluno();
drop trigger if exists whitelist_historico_turma_delete on public.whitelist;
create trigger whitelist_historico_turma_delete
before delete on public.whitelist
for each row execute function private.registrar_historico_turma_aluno();

-- Turmas futuras já nascem prontas para a edição atual do conteúdo.
create or replace function private.seed_turma_semanas()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
begin
  insert into public.turma_semanas (turma_id, semana_key, liberada, liberada_em)
  values
    (new.id, 'semana-0', false, null),
    (new.id, 'semana-1', false, null),
    (new.id, 'semana-2', false, null),
    (new.id, 'semana-3', false, null),
    (new.id, 'semana-4', false, null);

  insert into public.turma_conteudo_versoes (turma_id, etapa_key, versao)
  values
    (new.id, 'semana-0', 'v1'),
    (new.id, 'semana-1', 'v1'),
    (new.id, 'semana-2', 'v1'),
    (new.id, 'semana-3', 'v1'),
    (new.id, 'semana-4', 'v1');
  return new;
end;
$$;

revoke all on function private.seed_turma_semanas() from public, anon, authenticated;

alter table public.aluno_turmas enable row level security;
alter table public.turma_conteudo_versoes enable row level security;
revoke all on table public.aluno_turmas from public, anon, authenticated, service_role;
revoke all on table public.turma_conteudo_versoes from public, anon, authenticated, service_role;
grant select, insert, update, delete on table public.aluno_turmas to service_role;
grant select, insert, update, delete on table public.turma_conteudo_versoes to service_role;
revoke all on sequence public.aluno_turmas_id_seq from public, anon, authenticated, service_role;
grant usage, select on sequence public.aluno_turmas_id_seq to service_role;

commit;
