-- Dúvidas ricas: texto formatado + anexos (imagens e vídeos) + resposta do admin.
-- Aplicada no projeto pajdmyujulamgxrpypmo em 18/07/2026 via MCP.
alter table public.leituras add column if not exists duvida_html text;
alter table public.leituras add column if not exists resposta_html text;
alter table public.leituras add column if not exists respondida_em timestamptz;

create table if not exists public.leitura_anexos (
  id bigint generated by default as identity primary key,
  leitura_id bigint not null references public.leituras(id) on delete cascade,
  file text not null unique,
  tipo text not null check (tipo in ('imagem','video')),
  bytes bigint not null check (bytes > 0),
  criado_em timestamptz not null default now(),
  constraint leitura_anexos_file_tamanho check (char_length(file) between 1 and 1024)
);
create index if not exists leitura_anexos_leitura_id_idx on public.leitura_anexos(leitura_id);
alter table public.leitura_anexos enable row level security;
revoke all on public.leitura_anexos from anon, authenticated;
-- Sem policies: acesso só via servidor (secret key), depois dos gates.

insert into storage.buckets (id, name, public, file_size_limit)
values ('duvidas', 'duvidas', false, 104857600)
on conflict (id) do update set public = false, file_size_limit = 104857600;
