begin;

-- Respostas são separadas das publicações para que o feed mantenha a ordem
-- principal e cada conversa possa crescer em uma árvore própria.
create table if not exists public.post_respostas (
  id bigint generated by default as identity primary key,
  post_id bigint not null references public.posts(id) on delete cascade,
  parent_id bigint,
  user_id uuid not null references auth.users(id) on delete cascade,
  autor text not null check (char_length(autor) between 1 and 160),
  texto text not null check (char_length(texto) between 1 and 6000),
  conteudo_html text not null check (char_length(conteudo_html) between 1 and 50000),
  deletado boolean not null default false,
  created_at timestamptz not null default now(),

  constraint post_respostas_id_post_unique unique (id, post_id),
  constraint post_respostas_parent_mesmo_post_fk
    foreign key (parent_id, post_id)
    references public.post_respostas(id, post_id)
    on delete cascade,
  constraint post_respostas_nao_responde_a_si_mesma check (parent_id is null or parent_id <> id)
);

comment on table public.post_respostas is
  'Respostas server-only das publicações da comunidade, com suporte a threads aninhadas.';

create index if not exists post_respostas_feed_idx
  on public.post_respostas (post_id, created_at)
  where not deletado;
create index if not exists post_respostas_parent_idx
  on public.post_respostas (parent_id, created_at)
  where not deletado and parent_id is not null;

alter table public.post_respostas enable row level security;
revoke all on table public.post_respostas from public, anon, authenticated, service_role;
grant select, insert, update, delete on table public.post_respostas to service_role;
revoke all on sequence public.post_respostas_id_seq from public, anon, authenticated, service_role;
grant usage, select on sequence public.post_respostas_id_seq to service_role;

commit;
