-- Baseline reproduzível da área de membros.
-- Em um projeto que já contém estas tabelas, faça `supabase db pull` e reconcilie
-- o histórico antes de aplicar: esta migração foi escrita para um banco novo.

create schema if not exists private;
revoke all on schema private from public, anon, authenticated;

create table public.turmas (
  id bigint generated by default as identity primary key,
  nome text not null check (char_length(nome) between 1 and 160),
  inicio date,
  fim date,
  acesso_ate timestamptz,
  criado_em timestamptz not null default now(),
  constraint turmas_periodo_valido check (fim is null or inicio is null or fim >= inicio)
);

create table public.whitelist (
  email text primary key,
  nome text check (nome is null or char_length(nome) <= 160),
  turma_id bigint references public.turmas(id) on delete set null,
  expira_em timestamptz,
  criado_em timestamptz not null default now(),
  constraint whitelist_email_normalizado check (
    email = lower(btrim(email)) and email like '%_@_%._%'
  )
);

create index whitelist_turma_id_idx on public.whitelist(turma_id);

create table public.admins (
  email text primary key,
  criado_em timestamptz not null default now(),
  constraint admins_email_normalizado check (
    email = lower(btrim(email)) and email like '%_@_%._%'
  )
);

create table public.downloads (
  id bigint generated by default as identity primary key,
  tag text check (tag is null or char_length(tag) <= 80),
  titulo text not null check (char_length(titulo) between 1 and 200),
  "desc" text check ("desc" is null or char_length("desc") <= 1200),
  ordem integer not null default 0,
  criado_em timestamptz not null default now()
);

create index downloads_ordem_idx on public.downloads(ordem, id);

create table public.arquivos (
  id bigint generated by default as identity primary key,
  download_id bigint not null references public.downloads(id) on delete cascade,
  file text not null check (char_length(file) between 1 and 1024),
  versao integer not null check (versao > 0),
  nota text check (nota is null or char_length(nota) <= 500),
  ativo boolean not null default false,
  criado_em timestamptz not null default now(),
  unique (download_id, versao),
  unique (file)
);

create index arquivos_download_id_idx on public.arquivos(download_id);
create unique index arquivos_um_ativo_por_download_idx
  on public.arquivos(download_id)
  where ativo;

create table public.posts (
  id bigint generated by default as identity primary key,
  autor text not null check (char_length(autor) between 1 and 160),
  email text not null,
  texto text not null check (char_length(texto) between 1 and 3000),
  created_at timestamptz not null default now(),
  fixado boolean not null default false,
  deletado boolean not null default false,
  constraint posts_email_normalizado check (email = lower(btrim(email)))
);

create index posts_feed_idx
  on public.posts(fixado desc, created_at desc)
  where not deletado;

create table public.eventos (
  id bigint generated by default as identity primary key,
  email text not null,
  tipo text not null check (char_length(tipo) between 1 and 80),
  ref bigint,
  criado_em timestamptz not null default now(),
  constraint eventos_email_normalizado check (email = lower(btrim(email)))
);

create index eventos_email_tipo_criado_idx
  on public.eventos(email, tipo, criado_em desc);
create index eventos_tipo_criado_idx on public.eventos(tipo, criado_em desc);

create or replace function private.is_active_member()
returns boolean
language sql
stable
security definer
set search_path = ''
as $$
  select exists (
    select 1
    from public.whitelist as w
    left join public.turmas as t on t.id = w.turma_id
    where w.email = lower(coalesce((select auth.jwt() ->> 'email'), ''))
      and (
        coalesce(w.expira_em, t.acesso_ate) is null
        or coalesce(w.expira_em, t.acesso_ate) > now()
      )
  );
$$;

revoke all on function private.is_active_member() from public, anon;
grant usage on schema private to authenticated;
grant execute on function private.is_active_member() to authenticated;

alter table public.turmas enable row level security;
alter table public.whitelist enable row level security;
alter table public.admins enable row level security;
alter table public.downloads enable row level security;
alter table public.arquivos enable row level security;
alter table public.posts enable row level security;
alter table public.eventos enable row level security;

revoke all on all tables in schema public from anon, authenticated;
revoke all on all sequences in schema public from anon, authenticated;
alter default privileges in schema public revoke all on tables from anon, authenticated;
alter default privileges in schema public revoke all on sequences from anon, authenticated;

grant usage on schema public to authenticated;
grant select on public.downloads to authenticated;

create policy "membros ativos leem downloads"
on public.downloads
for select
to authenticated
using ((select private.is_active_member()));

-- O app lê/escreve as demais tabelas apenas no servidor, depois dos gates de
-- membro/admin, usando a secret key. Nenhuma tabela sensível é exposta ao anon.

insert into storage.buckets (id, name, public)
values ('materiais', 'materiais', false)
on conflict (id) do update set public = false;
