-- Materiais líveis dentro do app + registro de leitura por aluno.
-- (quem leu, tempo de tela, status: lido / entendido / com dúvidas)
-- Aplicada no projeto pajdmyujulamgxrpypmo em 18/07/2026 via MCP.

alter table public.downloads
  add column if not exists modo text not null default 'leitura';

alter table public.downloads
  drop constraint if exists downloads_modo_valido;

alter table public.downloads
  add constraint downloads_modo_valido check (modo in ('leitura','download'));

comment on column public.downloads.modo is
  'leitura: abre dentro do app com registro de leitura; download: arquivo baixável (kits, zips).';

create table if not exists public.leituras (
  id bigint generated by default as identity primary key,
  download_id bigint not null references public.downloads(id) on delete cascade,
  email text not null,
  segundos integer not null default 0 check (segundos >= 0),
  status text check (status in ('lido','entendido','duvida')),
  duvida text check (duvida is null or char_length(duvida) <= 2000),
  primeiro_acesso timestamptz not null default now(),
  ultimo_acesso timestamptz not null default now(),
  status_em timestamptz,
  unique (download_id, email),
  constraint leituras_email_normalizado check (email = lower(btrim(email)))
);

create index if not exists leituras_download_id_idx on public.leituras(download_id);
create index if not exists leituras_email_idx on public.leituras(email);

alter table public.leituras enable row level security;
revoke all on public.leituras from anon, authenticated;
-- Sem policies de propósito: o app lê e escreve apenas no servidor
-- (secret key), depois dos gates de membro/admin.

-- A RPC de incremento atômico entra ao fim da cadeia, já como SECURITY
-- INVOKER, depois de todos os objetos privados usados pelo aplicativo.
